---
- hosts: 
   - CENTOS7-RED-GOLD
  # set hostanme and register the server with spacewalk and update the server
  tasks:
    - name: "set hostname fact"
      raw: hostnamectl set-hostname {{ host_name }} --static
      #set_fact: testvar1={{ new_hostname }}
       #when: "'new' in new_hostname"
    - name: Register with activationkey and enable extended update support
      rhn_register:
        state: present
        server_url: https://192.168.0.50/XMLRPC
        activationkey: 1-222333444
        #channels: {{ channel }},{{ channel1 }},{{ channel2 }},{{ channel3 }}

     #- name: upgrade all packages
     #  yum:
     #    name: '*'
     #    state: latest
